//  Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nvidia/nvsentinel/pkg/client-go/client/versioned/typed/device/v1alpha1"
	grpc "google.golang.org/grpc"
	testing "k8s.io/client-go/testing"
)

type FakeDeviceV1alpha1 struct {
	*testing.Fake
}

// ClientConn returns nil for fake clientsets. There is no real gRPC connection.
func (c *FakeDeviceV1alpha1) ClientConn() grpc.ClientConnInterface {
	return nil
}

func (c *FakeDeviceV1alpha1) GPUs() v1alpha1.GPUInterface {
	return newFakeGPUs(c)
}
