//  Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	devicev1alpha1 "github.com/nvidia/nvsentinel/api/device/v1alpha1"
	v1alpha1 "github.com/nvidia/nvsentinel/pkg/client-go/client/versioned/typed/device/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// GPUsGetter has a method to return a GPUInterface.
// A group's client should implement this interface.
type GPUsGetter interface {
	GPUs() v1alpha1.GPUInterface
}

// fakeGPUs implements GPUInterface
type fakeGPUs struct {
	Fake *FakeDeviceV1alpha1
}

// newFakeGPUs returns a fakeGPUs
func newFakeGPUs(fake *FakeDeviceV1alpha1) v1alpha1.GPUInterface {
	return &fakeGPUs{
		Fake: fake,
	}
}

func (c *fakeGPUs) Resource() schema.GroupVersionResource {
	return devicev1alpha1.SchemeGroupVersion.WithResource("gpus")
}

func (c *fakeGPUs) Kind() schema.GroupVersionKind {
	return devicev1alpha1.SchemeGroupVersion.WithKind("GPU")
}

func (c *fakeGPUs) GetNamespace() string {
	if c == nil {
		return ""
	}
	return ""
}

// Get takes name of the GPU, and returns the corresponding GPU object, and an error if there is any.
func (c *fakeGPUs) Get(ctx context.Context, name string, opts v1.GetOptions) (result *devicev1alpha1.GPU, err error) {
	emptyResult := &devicev1alpha1.GPU{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(c.Resource(), name, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*devicev1alpha1.GPU), err
}

// List takes label and field selectors, and returns the list of GPUs that match those selectors.
func (c *fakeGPUs) List(ctx context.Context, opts v1.ListOptions) (result *devicev1alpha1.GPUList, err error) {
	emptyResult := &devicev1alpha1.GPUList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(c.Resource(), c.Kind(), opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*devicev1alpha1.GPUList), err
}

// Watch returns a watch.Interface that watches the requested GPUs.
func (c *fakeGPUs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(devicev1alpha1.SchemeGroupVersion.WithResource("gpus"), opts))
}

// Create takes the representation of a gPU and creates it.  Returns the server's representation of the gPU, and an error, if there is any.
func (c *fakeGPUs) Create(ctx context.Context, gPU *devicev1alpha1.GPU, opts v1.CreateOptions) (result *devicev1alpha1.GPU, err error) {
	emptyResult := &devicev1alpha1.GPU{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(c.Resource(), gPU, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*devicev1alpha1.GPU), err
}

// Update takes the representation of a gPU and updates it. Returns the server's representation of the gPU, and an error, if there is any.
func (c *fakeGPUs) Update(ctx context.Context, gPU *devicev1alpha1.GPU, opts v1.UpdateOptions) (result *devicev1alpha1.GPU, err error) {
	emptyResult := &devicev1alpha1.GPU{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(c.Resource(), gPU, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*devicev1alpha1.GPU), err
}

func (c *fakeGPUs) UpdateStatus(ctx context.Context, gPU *devicev1alpha1.GPU, opts v1.UpdateOptions) (*devicev1alpha1.GPU, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(c.Resource(), "status", gPU, opts), &devicev1alpha1.GPU{})
	if obj == nil {
		return nil, err
	}
	return obj.(*devicev1alpha1.GPU), err
}

// Delete takes name of the gPU and deletes it. Returns an error if one occurs.
func (c *fakeGPUs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(c.Resource(), name, opts), &devicev1alpha1.GPU{})
	return err
}
