//  Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	devicev1alpha1 "github.com/nvidia/nvsentinel/api/device/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GPULister helps list GPUs.
// All objects returned here must be treated as read-only.
type GPULister interface {
	// List lists all GPUs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*devicev1alpha1.GPU, err error)
	// Get retrieves the GPU from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*devicev1alpha1.GPU, error)
	GPUListerExpansion
}

// gPULister implements the GPULister interface.
type gPULister struct {
	listers.ResourceIndexer[*devicev1alpha1.GPU]
}

// NewGPULister returns a new GPULister.
func NewGPULister(indexer cache.Indexer) GPULister {
	return &gPULister{listers.New[*devicev1alpha1.GPU](indexer, devicev1alpha1.Resource("gpu"))}
}
